### ISSUE TITLE
Radio app no longer available in OpenStore for PinePhone

### ISSUE THREAD

**Issue by dtarrant2019** [patrickjane/ut-radio#10]
I have been using this app successfully on my PinePhone UBports UT CE until recently.
Today I tried to re-install it, but cannot find it in OpenStore.

Today I was able to install it from OpenStore on my BQ Aquaris HD tablet.

**Comment by patrickjane** [comment]
Hey, what exactly is the issue? :) 

Its here: https://open-store.io/app/radio.s710

**Comment by dtarrant2019** [comment]
It is in OpenStore when searched from my BQ tablet, but is not listed when I search from my PinePhone.
Bizarre. May be a bug in my re-installation of UT on my PinePhone.
I will investigate further.
Thanks for your response.

**Comment by patrickjane** [comment]
To be honest, I dont know how open store determines whether or not to show an app on device. Probably its determined by architecture. Is PinePhone arm64 or armhf? Is there even other architectures?

**Comment by patrickjane** [comment]
Oh one thing though. I have updated the app recently to the latest ubuntu sdk. Maybe you're not on the latest OTA on your PinePhone, and this is the reason it won't show?

**Comment by dtarrant2019** [comment]
Funny you should say that. I wondered why some of the icons were different and checked the date of the boot image:
2018!!! :(
I hang my head in shame.

**Comment by dtarrant2019** [comment]
Well, I am pleased to confirm that now that I have installed an up-to-date version of UT, your Radio app now appears in open store.
Thanks for your patience.

**Comment by patrickjane** [comment]
Nice. Glad it works.
