### ISSUE TITLE
Not Working On Lenovo TB-X605F Tablet

### ISSUE THREAD

**Issue by dtarrant2019** [patrickjane/ut-radio#11]
Not possible to search for internet radio streams.
This app works for me on Nexus 4 and BQ Aquaris M10 running Ubuntu Touch.
User interface is un-responsive on Lenovo TB-X605F
All other apps from OpenStore that I've installed on this device are working as expected.

**Comment by dtarrant2019** [comment]
This app also works well on PinePhone.

**Comment by patrickjane** [comment]
I suggest you consult the device porter then, I guess there is not much which can be done from my side. The app does not contain any code which is device-specific. It only contains generic QML code. If this does not run on a specific device, its either a QT issue or a device issue.

Also make youre that UT on your device is up to date.

**Comment by dtarrant2019** [comment]
Understood. I wondered if it could be an issue with the port.
I will do as you suggest and start by making sure that UT is up to date.

**Comment by dtarrant2019** [comment]
I have investigated the status of the port and it is known to have a number of issues which need to be fixed.
So maybe when the port is further advaned, your app will work fine.

**Comment by patrickjane** [comment]
Alright.
