### ISSUE TITLE
Impossible to search and add new stations

### ISSUE THREAD

**Issue by gbdomubpkm** [patrickjane/ut-radio#12]
Volla, nexus 5, bq E5HD..
Radio seems to be broken for searching and adding new stations and this, i don't know since when and why. Maybe before OTA-22. Can you confirm this ?

**Comment by patrickjane** [comment]
Thanks for the hint. Indeed on my Vollaphone the search & URL buttons are not working. I will investigate it.

**Comment by patrickjane** [comment]
Fixed with [335781b](https://github.com/patrickjane/ut-radio/commit/335781ba1a72d3a3f3a528c8863309a4913b014d) & published to open-store as version 1.4.3.

**Comment by gbdomubpkm** [comment]
> Fixed with [335781b](https://github.com/patrickjane/ut-radio/commit/335781ba1a72d3a3f3a528c8863309a4913b014d) & published to open-store as version 1.4.3.

Thank you !
