### ISSUE TITLE
Feature Request Metadata

### ISSUE THREAD

**Issue by bigbrotherisstillwatching** [patrickjane/ut-radio#14]
When playing a stream, artist and songtitle are shown in the systems media playback control (or whatever it is called; i hope you know, what i mean). But sometimes, e.g. when playing a mix from "1Mix Radio Trance", the text is too long to show all of it. Is it possible to show this as a scrollable text like the station name in the app?

Greetings bbisw

**Comment by patrickjane** [comment]
Hi,

thanks for the feedback. If you run the app on desktop (clone + `clickable desktop`), it will show the song title in the scrolling text. See code at https://github.com/patrickjane/ut-radio/blob/ee3c8d60bc4adc3b40c0ec5ecd802556bb44fa1d/qml/pages/MainPage.qml#L74C13-L74C29

However, on device, the audio system does not provide the song title metadata, therefore it cannot be displayed. This is an issue on the QT/UT side, which I can not influence.

**Comment by bigbrotherisstillwatching** [comment]
I think you got me wrong. Look in the screenshot. There you can see that artist and songtitle aren't displayed in full length but with three points at the end.

**Comment by bigbrotherisstillwatching** [comment]
![screenshot20231205_180323479](https://github.com/patrickjane/ut-radio/assets/140657673/a217e9af-7e48-4abc-9e30-050746ab1aab)

I think you got me wrong. Look at the screenshot. Artist and songtitle are displayed, but with three points at the end and not in full length. Is it possible to show this as a scrolling text? It's pity, that it isn't possible in the app itself.

Bye bbisw

**Comment by patrickjane** [comment]
This is part of ubuntu touch, not my app. Therefore there’s nothing I can do about it I‘m afraid.

**Comment by bigbrotherisstillwatching** [comment]
A pity! But no problem...i can look for myself on the website of the stream provider to know what is playing at the moment.

OK, but i think there's another problem with the scolling text in the app. When i start the app the text scrolls, but when changing the station scrolling stops and looks like in the screenshot. It starts at the middle and continues from the left.

![screenshot20231205_212537744](https://github.com/patrickjane/ut-radio/assets/140657673/f9f47ffc-0d01-4836-a114-d0bd253f50f6)

**Comment by patrickjane** [comment]
Are you sure the text is long enough? I think it does not scroll when the text fits on the screen.

**Comment by bigbrotherisstillwatching** [comment]
Yes, you're right. I've tested it and it only stops scrolling, when the text fits in the screen. It looks weird, but no problem.

OK, then let's close this thread.

Thanks for your time.

Kind regards bbisw

**Comment by bigbrotherisstillwatching** [comment]
Sorry for re-opening as i have one more question:

As the system shows artist & songtitle, isn't it possible to take the metadata information from there, than write it to a fifo pipe, a normal external text file or use stdin/stdout to read the information from this file or pipe and than show it in the app?

Sorry when this is a stupid questions, as i have no idea about QT/QML or C++. Maybe the app already does/tries this?!

Bye

**Comment by patrickjane** [comment]
Apps are sandboxed, and cannot access arbitrary filesystems. Furthermore, if something shall happen outside of my app, how could I implement this *with* my app?
This is out of scope for my app, unfortunately.

**Comment by bigbrotherisstillwatching** [comment]
As a little workaround you can install [https://github.com/altdesktop/playerctl](url) and use this command in terminal:
`playerctl metadata title`
I've tried to run and read the output of this command from within the app with QProcess or system() but without success.

**Comment by patrickjane** [comment]
I think you would be better off asking UT devs, which would hopefully benefit everyone, rather then build some fragile workaround for a single app :)

**Comment by bigbrotherisstillwatching** [comment]
You're right. Maybe i'll ask there. I had to see that it's not as easy as i thought to integrate such thing with my knowledge near zero and the help of tutorials. But nevermind, this way i've learned a little bit about QML/QT and C++. 8-)

**Comment by bigbrotherisstillwatching** [comment]
After weeks and hundreds of trials and errors i have a version with working metadata now. As unconfined app i can run system commands with QProcess. Had to find that out by reading many forum threads and tutorials. You said it's not worth the work, but this is one of the few internet radio apps (not webapps) i've found so far. I want to have metadata information and so i made the effort to integrate it. It's not perfect, but, so far, just works as expected. Have a look and try:

(https://github.com/bigbrotherisstillwatching/ut-radio_metadata)
