### ISSUE TITLE
Fehler 2

### ISSUE THREAD

**Issue by chrisewcs** [patrickjane/ut-radio#4]
Ich nutze ut-radio auf dem VollaPhone.
Seit kurzem kommt immer Fehler 2.
Kein sound

**Comment by patrickjane** [comment]
Hast du UT auf OTA-19 aktualisiert? Wenn ja, kam der Fehler davor auch schon?

**Comment by patrickjane** [comment]
Ergänzung:
Ich kann das Problem auf meinem Gerät nicht nachstellen. Der Fehlercode "2" bedeutet allerdings, dass das Format des Streams nicht unterstützt wird. Entweder ist also die URL des Streams falsch, oder der Stream kann einfach nicht abgespielt werden, da, wie gesagt, das Format nicht unterstützt wird. Sollte letzteres der Fall sein, kann ich daran nichts ändern, da habe ich keinen Einfluss drauf.

Weiterhin wird im nächsten Update die Fehlermeldung verbessert; statt der Fehlernummer wird dann eine aussagekräftigere Fehlermeldung angezeigt werden.

**Comment by chrisewcs** [comment]
Hallo,
Zu ers mal ich finde deine app super.
Eine Frage hätte ich noch.
Heißt das es fehlen bei Ubuntu Touch eventuell notwendige Bibliotheken.
Auf meinem Desktop mit Linux Mint funktioniert der Stream mit VLC 

Danke 
Christian 



Am Fri, 24 Sep 2021 02:29:29 -0700, patrickjane schrieb:
> Ergänzung:
> Ich kann das Problem auf meinem Gerät nicht nachstellen. Der 
> Fehlercode "2" bedeutet allerdings, dass das Format des Streams 
> nicht unterstützt wird. Entweder ist also die URL des Streams 
> falsch, oder der Stream kann einfach nicht abgespielt werden, 
> da, wie gesagt, das Format nicht unterstützt wird. Sollte 
> letzteres der Fall sein, kann ich daran nichts ändern, da habe 
> ich keinen Einfluss drauf.
> 
> Weiterhin wird im nächsten Update die Fehlermeldung verbessert; 
> statt der Fehlernummer wird dann eine aussagekräftigere 
> Fehlermeldung angezeigt werden.
> 


-- 
Sent with Dekko - the convergent email app

**Comment by patrickjane** [comment]
> Heißt das es fehlen bei Ubuntu Touch eventuell notwendige Bibliotheken. Auf meinem Desktop mit Linux Mint funktioniert der Stream mit VLC

Das bedeutet in erster Linie, dass der QT Mediaplayer von Ubuntu Touch den Stream nicht abspielen kann. VLC ist wieder eine andere Sache, da VLC sicherlich jedes Format auf der Welt unterstützt.
