### ISSUE TITLE
[feature request] recording an audio stream

### ISSUE THREAD

**Issue by gbdomubpkm** [patrickjane/ut-radio#5]
Hello.
Would it be possible to add a stream recording function when the radio is playing,  with a recording pose function if possible ?
Thank you again for your very usefull radio app.

**Comment by patrickjane** [comment]
Not sure if it would be possible, but I think it would not be legal in the first place.

**Comment by gbdomubpkm** [comment]
Are you telling me that it is not allowed to record a radio stream for private use and listen to it again later??  Even a news programme broadcast by a news channel like 'France Inter' ?

**Comment by patrickjane** [comment]
Well, at least for germany I am not sure. But this also is not the focus of the app :) So I would like to avoid introducing this kind of functionality.
