### ISSUE TITLE
ut-radio stream will not play over bluetooth to ear buds.

### ISSUE THREAD

**Issue by dtarrant2019** [patrickjane/ut-radio#9]
ut-radio plays fine on my PinePhone with wired ear buds, but not with bluetooth ear buds.
However, audio from my Music folder plays perfectly over bluetooth.

**Comment by patrickjane** [comment]
Thanks for the feedback. I have just tried with my airpods, and I did not have any issues:
![screenshot20220124_080712019](https://user-images.githubusercontent.com/1404715/150737552-a5a7716d-6610-496d-a7b5-6c045881592e.png)

As the bluetooth connection and audio playback is actually controlled by the operating system, I doubt that there is anything inside my app which can influence the bluetooth connectivity, so probably I can't do much about this issue.

Do you have the latest version installed? It is built with the latest Ubuntu Touch SDK, as there have been changes in Ubuntu Touch regarding audio playback in the latest OTA.

**Comment by dtarrant2019** [comment]
Just tested with Nexus-4 running OTA-21 and Sony bluetooth headphones and I am pleased to confirm ut-radio  is receiving BBC radio streams loud and clear.
I'm running latest devel release on PinePhone and bluetooth is unstable. Often PinePhone requires a restart before it connects.
Anyhow, many thanks for ut-radio app, I love it!  :)

**Comment by patrickjane** [comment]
Great, glad it works now.
